(function(){
const clone=x=>JSON.parse(JSON.stringify(x)), original=clone(window.SHIZUKU_DATA);let data=clone(original);
const frame=document.getElementById('frame'),nav=document.getElementById('nav'),panels=document.getElementById('panels');let activePanel='brand',dragState=null,currentDevice='desktop';
const sections=[['Brand & Logo','brand'],['Page Styles','styles'],['Hero','hero'],['Philosophy','philosophy'],['Our Story','story'],['Our Tea','tea'],['Why Us','why'],['Tea Library','library'],['Japan Matcha Atlas','atlas'],['Menu','menu'],['Little Updates','updates'],['Contact','contact']];

function ensureDefaults(){
 data.atlas=data.atlas||{eyebrow:'MATCHA ATLAS',title:'Explore Japan through tea.',subtitle:'Regions, styles and cultivars in one place.',body:'Select a region to discover its tea character and related cultivars.',mapImage:'assets/japan-map.svg',regions:[
  {name:'Uji, Kyoto',description:'Historic tea region known for refined aroma, umami and elegant texture.',cultivars:['Uji Midori','Samidori','Gokou','Asahi'],notes:'Refined · Umami · Aromatic'},
  {name:'Yame, Fukuoka',description:'Known for shaded teas with depth, sweetness and a smooth finish.',cultivars:['Yabukita','Okumidori'],notes:'Deep · Sweet · Smooth'},
  {name:'Nishio, Aichi',description:'A major matcha-producing area with a rich body and approachable balance.',cultivars:['Yabukita','Samidori'],notes:'Rich · Balanced · Full-bodied'},
  {name:'Shizuoka',description:'Japan’s largest tea-producing prefecture, offering a broad range of styles.',cultivars:['Yabukita','Okuyutaka'],notes:'Fresh · Green · Versatile'}
 ]};
 const migrate=(o)=>{if(!o||typeof o!=='object')return; if(o.image){
  if(!o.imagePositionDesktop)o.imagePositionDesktop=o.imagePosition||{x:50,y:50};
  if(!o.imagePositionMobile)o.imagePositionMobile=o.imagePosition||{x:50,y:50};
  if(o.imageScaleDesktop==null)o.imageScaleDesktop=o.imageScale||1;
  if(o.imageScaleMobile==null)o.imageScaleMobile=o.imageScale||1;
 }
 Object.values(o).forEach(v=>{if(Array.isArray(v))v.forEach(migrate);else if(v&&typeof v==='object')migrate(v)});
 };
 migrate(data);
}
ensureDefaults();
function imageState(base){const cap=currentDevice[0].toUpperCase()+currentDevice.slice(1);return {posPath:base+'.imagePosition'+cap,scalePath:base+'.imageScale'+cap,pos:get(base+'.imagePosition'+cap)||{x:50,y:50},scale:get(base+'.imageScale'+cap)||1}}

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function get(path){return path.split('.').reduce((o,k)=>o?.[k],data)}
function assign(path,val){const ks=path.split('.');let o=data;ks.slice(0,-1).forEach(k=>{if(o[k]==null)o[k]={};o=o[k]});o[ks.at(-1)]=val}
function set(path,val){const old=get(path);if(Array.isArray(old))assign(path,String(val).split(',').map(x=>x.trim()).filter(Boolean));else if(typeof old==='number')assign(path,Number(val));else if(typeof old==='boolean')assign(path,val==='true'||val===true);else assign(path,val)}
function imageEditor(path,value){const base=path.replace(/\.image$/,''),st=imageState(base);return `<label class="field image-field"><span>Image · adjusting ${currentDevice}</span><input type="file" accept="image/*" data-image-path="${path}"><div class="image-crop" data-image-editor="${base}" title="Drag the image to reposition it"><img src="${esc(value)}" alt="" style="object-position:${st.pos.x}% ${st.pos.y}%;transform:scale(${st.scale});transform-origin:${st.pos.x}% ${st.pos.y}%"></div><div class="image-tools"><small>Drag photo to adjust · ${currentDevice}</small><label>Zoom <input type="range" min="1" max="2.5" step="0.05" value="${st.scale}" data-image-scale="${base}"></label><button type="button" data-image-reset="${base}">Reset</button></div></label>`}
function field(label,path,value,type='text',options=[]){if(type==='textarea')return `<label class="field"><span>${label}</span><textarea data-path="${path}">${esc(value)}</textarea></label>`;if(type==='select')return `<label class="field"><span>${label}</span><select data-path="${path}">${options.map(x=>`<option ${x===value?'selected':''}>${esc(x)}</option>`).join('')}</select></label>`;if(type==='image')return imageEditor(path,value);return `<label class="field"><span>${label}</span><input data-path="${path}" type="${type}" value="${esc(value)}"></label>`}
function positionPad(label,path,value){const v=value||{x:50,y:50};return `<div class="position-control"><span>${label}</span><div class="position-pad" data-position-pad="${path}"><i></i><b style="left:${v.x}%;top:${v.y}%"></b></div><small>X <output data-position-x="${path}">${Math.round(v.x)}</output>% · Y <output data-position-y="${path}">${Math.round(v.y)}</output>%</small></div>`}
function textSet(prefix,obj,includeSubtitle=true){return `${field('Eyebrow',prefix+'.eyebrow',obj.eyebrow||'')}${field('Title',prefix+'.title',obj.title||'','textarea')}${includeSubtitle?field('Subtitle (optional)',prefix+'.subtitle',obj.subtitle||'','textarea'):''}${obj.body!==undefined?field('Body',prefix+'.body',obj.body,'textarea'):''}`}
function itemActions(type,index){return `<div class="small-actions"><button type="button" class="drag-handle" draggable="true" data-drag-list="${type}" data-index="${index}" aria-label="Drag to reorder"><i></i><i></i><i></i><i></i><i></i><i></i></button><button class="delete" data-delete="${type}" data-index="${index}">Delete</button></div>`}
function pageStylePanel(){const fonts=['Gloock','DM Sans','Noto Serif JP','Playfair Display','Cormorant Garamond'];return Object.entries(data.sectionStyles).map(([k,s])=>`<div class="item"><h3>${k[0].toUpperCase()+k.slice(1)}</h3><div class="row">${field('Background',`sectionStyles.${k}.background`,s.background,'color')}${field('Title colour',`sectionStyles.${k}.titleColor`,s.titleColor,'color')}</div><div class="row">${field('Body colour',`sectionStyles.${k}.bodyColor`,s.bodyColor,'color')}${field('Title font',`sectionStyles.${k}.titleFont`,s.titleFont,'select',fonts)}</div><div class="row">${field('Desktop title size',`sectionStyles.${k}.titleSizeDesktop`,s.titleSizeDesktop,'number')}${field('Mobile title size',`sectionStyles.${k}.titleSizeMobile`,s.titleSizeMobile,'number')}</div><div class="row">${field('Body font',`sectionStyles.${k}.bodyFont`,s.bodyFont,'select',fonts)}${field('Body size',`sectionStyles.${k}.bodySize`,s.bodySize,'number')}</div></div>`).join('')}
function makePanels(){
 nav.innerHTML=sections.map((s,i)=>`<button data-panel="${s[1]}" class="${i?'':'active'}">${s[0]}</button>`).join('');
 panels.innerHTML=`
 <section class="panel active" data-panel="brand"><h2>Brand & Logo</h2><p>Change the logo file, colour and core links.</p><div class="group">${field('Logo image','brand.logo',data.brand.logo,'image')}<div class="row">${field('Logo colour','brand.logoColor',data.brand.logoColor,'color')}${field('Accent colour','brand.accent',data.brand.accent,'color')}</div><div class="row">${field('Desktop logo size','brand.logoDesktop',data.brand.logoDesktop,'number')}${field('Mobile logo size','brand.logoMobile',data.brand.logoMobile,'number')}</div><div class="row">${positionPad('Desktop logo position','brand.logoDesktopPosition',data.brand.logoDesktopPosition)}${positionPad('Mobile logo position','brand.logoMobilePosition',data.brand.logoMobilePosition)}</div>${field('Studio descriptor','brand.descriptor',data.brand.descriptor)}${field('Order URL','brand.orderUrl',data.brand.orderUrl)}${field('Instagram URL','brand.instagramUrl',data.brand.instagramUrl)}</div></section>
 <section class="panel" data-panel="styles"><h2>Page Styles</h2><p>Every page can use its own paper colour, font, text colour and size.</p><div class="group">${pageStylePanel()}</div></section>
 <section class="panel" data-panel="hero"><h2>Hero</h2><div class="group">${textSet('hero',data.hero)}${field('Hero image','hero.image',data.hero.image,'image')}</div></section>
 <section class="panel" data-panel="philosophy"><h2>Philosophy</h2><div class="group">${textSet('philosophy',data.philosophy)}</div></section>
 <section class="panel" data-panel="story"><h2>Our Story</h2><div class="group">${textSet('story',data.story,false)}${field('Subtitle (optional)','story.subtitle',data.story.subtitle,'textarea')}${field('Paragraph 1','story.paragraph1',data.story.paragraph1,'textarea')}${field('Paragraph 2','story.paragraph2',data.story.paragraph2,'textarea')}${field('Image','story.image',data.story.image,'image')}</div></section>
 <section class="panel" data-panel="tea"><h2>Our Tea</h2><p>Matcha and houjicha live together here.</p><div class="group">${textSet('tea',data.tea)}${data.tea.items.map((t,i)=>`<div class="item reorder-item" data-drop-list="tea.items" data-index="${i}"><div class="item-head"><h3>${esc(t.name)}</h3>${itemActions('tea.items',i)}</div>${field('Name',`tea.items.${i}.name`,t.name)}${field('Image',`tea.items.${i}.image`,t.image,'image')}${field('Origin',`tea.items.${i}.origin`,t.origin)}${field('Harvest / type',`tea.items.${i}.harvest`,t.harvest)}${field('Profile',`tea.items.${i}.profile`,t.profile)}${field('Finish',`tea.items.${i}.finish`,t.finish)}</div>`).join('')}<button class="add-btn" data-add="tea.items">+ Add tea powder</button></div></section>
 <section class="panel" data-panel="why"><h2>Why Us</h2><p>Add, delete and reorder topics freely.</p><div class="group">${textSet('why',data.why,false)}${field('Subtitle (optional)','why.subtitle',data.why.subtitle||'','textarea')}${data.why.items.map((w,i)=>`<div class="item reorder-item" data-drop-list="why.items" data-index="${i}"><div class="item-head"><h3>${esc(w.title)}</h3>${itemActions('why.items',i)}</div>${field('Title',`why.items.${i}.title`,w.title)}${field('Description',`why.items.${i}.body`,w.body,'textarea')}</div>`).join('')}<button class="add-btn" data-add="why.items">+ Add Why Us topic</button></div></section>
 <section class="panel" data-panel="library"><h2>Tea Library</h2><p>Edit or add knowledge topics and cultivar cards.</p><div class="group">${textSet('library',data.library)}<h3>Knowledge topics</h3>${data.library.topics.map((t,i)=>`<div class="item reorder-item" data-drop-list="library.topics" data-index="${i}"><div class="item-head"><h3>${esc(t.title)}</h3>${itemActions('library.topics',i)}</div>${field('ID',`library.topics.${i}.id`,t.id)}${field('Title',`library.topics.${i}.title`,t.title)}${field('Subtitle',`library.topics.${i}.subtitle`,t.subtitle,'textarea')}${field('Content',`library.topics.${i}.body`,t.body,'textarea')}${field('Image',`library.topics.${i}.image`,t.image,'image')}<button class="add-btn" data-preview-topic="${esc(t.id)}">Preview topic →</button></div>`).join('')}<button class="add-btn" data-add="library.topics">+ Add knowledge topic</button><h3 style="margin-top:30px">Cultivars</h3>${data.library.cultivars.map((c,i)=>`<div class="item reorder-item" data-drop-list="library.cultivars" data-index="${i}"><div class="item-head"><h3>${esc(c.name)}</h3>${itemActions('library.cultivars',i)}</div>${field('Name',`library.cultivars.${i}.name`,c.name)}${field('Region',`library.cultivars.${i}.region`,c.region)}${field('Image',`library.cultivars.${i}.image`,c.image,'image')}${field('Profile',`library.cultivars.${i}.profile`,c.profile,'textarea')}<div class="row">${field('Tag 1',`library.cultivars.${i}.tag1`,c.tag1)}${field('Tag 2',`library.cultivars.${i}.tag2`,c.tag2)}</div></div>`).join('')}<button class="add-btn" data-add="library.cultivars">+ Add cultivar</button></div></section>
 <section class="panel" data-panel="atlas"><h2>Japan Matcha Atlas</h2><p>Edit the map introduction and regional cultivar links.</p><div class="group">${textSet('atlas',data.atlas)}${field('Japan map image','atlas.mapImage',data.atlas.mapImage,'image')}<h3>Regions</h3>${data.atlas.regions.map((r,i)=>`<div class="item reorder-item" data-drop-list="atlas.regions" data-index="${i}"><div class="item-head"><h3>${esc(r.name)}</h3>${itemActions('atlas.regions',i)}</div>${field('Region name',`atlas.regions.${i}.name`,r.name)}${field('Description',`atlas.regions.${i}.description`,r.description,'textarea')}${field('Cultivars (comma separated)',`atlas.regions.${i}.cultivars`,Array.isArray(r.cultivars)?r.cultivars.join(', '):r.cultivars)}${field('Style notes',`atlas.regions.${i}.notes`,r.notes)}</div>`).join('')}<button class="add-btn" data-add="atlas.regions">+ Add region</button></div></section>
 <section class="panel" data-panel="menu"><h2>Menu</h2><p>Portrait photos stay intact. The colour card beside each drink is fully editable.</p><div class="group">${textSet('menuMeta',data.menuMeta,false)}${field('Subtitle (milk note)','menuMeta.subtitle',data.menuMeta.subtitle,'textarea')}${data.menu.map((m,i)=>`<div class="item reorder-item" data-drop-list="menu" data-index="${i}"><div class="item-head"><h3>${esc(m.name)}</h3>${itemActions('menu',i)}</div><div class="row">${field('Category',`menu.${i}.eyebrow`,m.eyebrow)}${field('Status',`menu.${i}.status`,m.status,'select',['published','draft'])}</div>${field('Name',`menu.${i}.name`,m.name)}${field('Subtitle (optional)',`menu.${i}.subtitle`,m.subtitle||'')}${field('Description',`menu.${i}.description`,m.description,'textarea')}<div class="row">${field('Price',`menu.${i}.price`,m.price)}${field('Milk option applies',`menu.${i}.milk`,String(m.milk),'select',['true','false'])}</div>${field('Photo',`menu.${i}.image`,m.image,'image')}<div class="row">${field('Colour card',`menu.${i}.cardColor`,m.cardColor,'color')}${field('Text colour',`menu.${i}.textColor`,m.textColor,'color')}</div></div>`).join('')}<button class="add-btn" data-add="menu">+ Add drink</button></div></section>
 <section class="panel" data-panel="updates"><h2>Little Updates</h2><p>Add up to five updates. Each can have a subtitle.</p><div class="group">${textSet('updatesMeta',data.updatesMeta,false)}${field('Subtitle','updatesMeta.subtitle',data.updatesMeta.subtitle,'textarea')}${data.updates.map((u,i)=>`<div class="item reorder-item" data-drop-list="updates" data-index="${i}"><div class="item-head"><h3>${esc(u.title)}</h3>${itemActions('updates',i)}</div><div class="row">${field('Date / label',`updates.${i}.date`,u.date)}${field('Status',`updates.${i}.status`,u.status,'select',['published','draft'])}</div>${field('Title',`updates.${i}.title`,u.title)}${field('Subtitle (optional)',`updates.${i}.subtitle`,u.subtitle||'')}${field('Body',`updates.${i}.body`,u.body,'textarea')}${field('Image',`updates.${i}.image`,u.image,'image')}${field('Card colour',`updates.${i}.cardColor`,u.cardColor,'color')}</div>`).join('')}<button class="add-btn" data-add="updates" ${data.updates.length>=5?'disabled':''}>+ Add update (max 5)</button></div></section>
 <section class="panel" data-panel="contact"><h2>Contact</h2><div class="group">${textSet('contact',data.contact,false)}${field('Subtitle','contact.subtitle',data.contact.subtitle||'','textarea')}${field('Collection information','contact.collection',data.contact.collection,'textarea')}${field('Instagram display','contact.instagram',data.contact.instagram)}${field('Closing message','contact.closing',data.contact.closing,'textarea')}</div></section>`;
 document.querySelectorAll('.nav button,.panel').forEach(x=>x.classList.remove('active'));document.querySelector(`.nav button[data-panel="${activePanel}"]`)?.classList.add('active');document.querySelector(`.panel[data-panel="${activePanel}"]`)?.classList.add('active');
}
function preview(){frame.contentWindow.postMessage({type:'SHIZUKU_PREVIEW',data},'*')}
function addItem(list){const templates={
 'tea.items':{name:'New tea',image:'assets/straight-matcha.jpg',origin:'Japan',harvest:'',profile:'',finish:''},
 'why.items':{title:'New detail',body:'Describe why it matters.'},
 'library.topics':{id:'new-topic-'+Date.now(),title:'New topic',subtitle:'',body:'',image:'assets/straight-matcha.jpg'},
 'library.cultivars':{name:'New cultivar',region:'Japan',image:'assets/cultivar-samidori.jpg',profile:'',tag1:'',tag2:''},
 'menu':{eyebrow:'NEW',name:'New drink',subtitle:'',description:'',price:'$0.00',image:'assets/matcha-latte.jpg',cardColor:'#dcebcf',textColor:'#173e31',milk:true,status:'draft'},
 'atlas.regions':{name:'New region',description:'',cultivars:[],notes:''},
 'updates':{date:'FROM THE LAB',title:'New update',subtitle:'',body:'',image:'assets/matcha-latte.jpg',cardColor:'#e9e2d4',status:'draft'}
};if(list==='updates'&&data.updates.length>=5)return;get(list).push(clone(templates[list]));makePanels();preview()}
function prepareImage(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=reject;r.onload=()=>{const im=new Image();im.onerror=reject;im.onload=()=>{const max=1800,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext('2d').drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL(file.type==='image/png'?'image/png':'image/jpeg',.88))};im.src=r.result};r.readAsDataURL(file)})}
nav.onclick=e=>{const b=e.target.closest('[data-panel]');if(!b)return;document.querySelectorAll('.nav button,.panel').forEach(x=>x.classList.remove('active'));activePanel=b.dataset.panel;b.classList.add('active');document.querySelector(`.panel[data-panel="${b.dataset.panel}"]`).classList.add('active');const map={brand:'home',styles:'home',hero:'home',philosophy:'philosophy',story:'story',tea:'tea',why:'why',library:'library',atlas:'library',menu:'menu',updates:'updates',contact:'contact'};frame.contentWindow.postMessage({type:'SHIZUKU_NAVIGATE',target:map[b.dataset.panel]},'*')};
panels.addEventListener('input',e=>{if(!e.target.dataset.path)return;set(e.target.dataset.path,e.target.value);preview()});
panels.addEventListener('change',async e=>{const path=e.target.dataset.imagePath,file=e.target.files?.[0];if(!path||!file)return;const val=await prepareImage(file);set(path,val);const base=path.replace(/\.image$/,'');assign(base+'.imagePositionDesktop',{x:50,y:50});assign(base+'.imagePositionMobile',{x:50,y:50});assign(base+'.imageScaleDesktop',1);assign(base+'.imageScaleMobile',1);const ed=e.target.parentElement.querySelector('.image-crop img');if(ed){ed.src=val;ed.style.objectPosition='50% 50%';ed.style.transform='scale(1)'}preview()});
panels.onclick=e=>{const add=e.target.closest('[data-add]');if(add){addItem(add.dataset.add);return}const del=e.target.closest('[data-delete]');if(del){get(del.dataset.delete).splice(Number(del.dataset.index),1);makePanels();preview();return}const resetImage=e.target.closest('[data-image-reset]');if(resetImage){const base=resetImage.dataset.imageReset;assign(base+'.imagePositionDesktop',{x:50,y:50});assign(base+'.imagePositionMobile',{x:50,y:50});assign(base+'.imageScaleDesktop',1);assign(base+'.imageScaleMobile',1);makePanels();preview();return}const topic=e.target.closest('[data-preview-topic]');if(topic){frame.contentWindow.postMessage({type:'SHIZUKU_OPEN_LIBRARY',topic:topic.dataset.previewTopic},'*')}};

// Six-dot drag handles: drag an item to its new position.
panels.addEventListener('dragstart',e=>{const h=e.target.closest('[data-drag-list]');if(!h)return;dragState={list:h.dataset.dragList,index:Number(h.dataset.index)};e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',JSON.stringify(dragState));h.closest('.reorder-item')?.classList.add('dragging')});
panels.addEventListener('dragend',()=>{document.querySelectorAll('.reorder-item').forEach(x=>x.classList.remove('dragging','drag-over'));dragState=null});
panels.addEventListener('dragover',e=>{const item=e.target.closest('[data-drop-list]');if(!item||!dragState||item.dataset.dropList!==dragState.list)return;e.preventDefault();document.querySelectorAll('.reorder-item.drag-over').forEach(x=>x.classList.remove('drag-over'));item.classList.add('drag-over')});
panels.addEventListener('drop',e=>{const item=e.target.closest('[data-drop-list]');if(!item||!dragState||item.dataset.dropList!==dragState.list)return;e.preventDefault();const a=get(dragState.list),from=dragState.index,to=Number(item.dataset.index);if(from!==to){const [moved]=a.splice(from,1);a.splice(to,0,moved)}makePanels();preview();dragState=null});

// Drag the logo dot on the cross-position pad.
function updatePositionPad(pad,clientX,clientY){const r=pad.getBoundingClientRect(),x=Math.max(0,Math.min(100,(clientX-r.left)/r.width*100)),y=Math.max(0,Math.min(100,(clientY-r.top)/r.height*100)),path=pad.dataset.positionPad;assign(path,{x,y});pad.querySelector('b').style.cssText=`left:${x}%;top:${y}%`;pad.parentElement.querySelector(`[data-position-x="${path}"]`).value=Math.round(x);pad.parentElement.querySelector(`[data-position-y="${path}"]`).value=Math.round(y);preview()}
panels.addEventListener('pointerdown',e=>{const pad=e.target.closest('[data-position-pad]');if(!pad)return;e.preventDefault();pad.setPointerCapture(e.pointerId);pad.dataset.dragging='1';updatePositionPad(pad,e.clientX,e.clientY)});
panels.addEventListener('pointermove',e=>{const pad=e.target.closest('[data-position-pad]')||document.querySelector('[data-position-pad][data-dragging="1"]');if(!pad||pad.dataset.dragging!=='1')return;updatePositionPad(pad,e.clientX,e.clientY)});
panels.addEventListener('pointerup',e=>{document.querySelectorAll('[data-position-pad][data-dragging="1"]').forEach(p=>{p.dataset.dragging='';try{p.releasePointerCapture(e.pointerId)}catch(_){}})});

// Drag any uploaded/existing photo inside its crop frame; slider controls zoom.
let imageDrag=null;
panels.addEventListener('pointerdown',e=>{const box=e.target.closest('[data-image-editor]');if(!box)return;e.preventDefault();const base=box.dataset.imageEditor,st=imageState(base),pos=st.pos;imageDrag={box,base,posPath:st.posPath,startX:e.clientX,startY:e.clientY,x:Number(pos.x??50),y:Number(pos.y??50)};box.setPointerCapture(e.pointerId);box.classList.add('is-dragging')});
panels.addEventListener('pointermove',e=>{if(!imageDrag)return;const r=imageDrag.box.getBoundingClientRect(),x=Math.max(0,Math.min(100,imageDrag.x-(e.clientX-imageDrag.startX)/r.width*100)),y=Math.max(0,Math.min(100,imageDrag.y-(e.clientY-imageDrag.startY)/r.height*100));assign(imageDrag.posPath,{x,y});const im=imageDrag.box.querySelector('img');im.style.objectPosition=`${x}% ${y}%`;im.style.transformOrigin=`${x}% ${y}%`;preview()});
panels.addEventListener('pointerup',e=>{if(!imageDrag)return;imageDrag.box.classList.remove('is-dragging');try{imageDrag.box.releasePointerCapture(e.pointerId)}catch(_){}imageDrag=null});
panels.addEventListener('input',e=>{const base=e.target.dataset.imageScale;if(!base)return;const scale=Number(e.target.value);const st=imageState(base);assign(st.scalePath,scale);const im=e.target.closest('.image-field').querySelector('.image-crop img');im.style.transform=`scale(${scale})`;preview()});


const DB_NAME='shizuku-cms',STORE='drafts',KEY='website-preview';
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function dbPut(value){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(value,KEY);tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}})}
async function dbGet(){const db=await openDB();return new Promise((resolve,reject)=>{const r=db.transaction(STORE,'readonly').objectStore(STORE).get(KEY);r.onsuccess=()=>{db.close();resolve(r.result||null)};r.onerror=()=>{db.close();reject(r.error)}})}
async function dbDelete(){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(KEY);tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}})}
document.getElementById('save').onclick=async()=>{const b=document.getElementById('save'),label=b.textContent;b.disabled=true;b.textContent='Saving…';try{await dbPut(data);b.textContent='Saved ✓'}catch(err){console.error(err);b.textContent='Save failed';alert('Preview could not be saved.')}setTimeout(()=>{b.disabled=false;b.textContent=label},1300)};
document.getElementById('reset').onclick=async()=>{if(!confirm('Reset draft and return to the current site-data.js?'))return;data=clone(original);ensureDefaults();await dbDelete();makePanels();preview()};
document.getElementById('export').onclick=()=>{const blob=new Blob(['window.SHIZUKU_DATA = '+JSON.stringify(data,null,2)+';\n'],{type:'text/javascript'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='site-data.js';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
document.querySelector('.devices').onclick=e=>{const b=e.target.closest('button');if(!b)return;currentDevice=b.dataset.device;document.querySelectorAll('.devices button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('preview').classList.toggle('mobile',currentDevice==='mobile');makePanels();preview()};
(async function initialise(){try{const saved=await dbGet();if(saved){data=clone(saved);ensureDefaults()}}catch(err){console.warn('Draft load failed',err)}makePanels();frame.addEventListener('load',preview,{once:true});preview()})();
})();
