(() => {
const clone=value=>JSON.parse(JSON.stringify(value));
if(!window.SHIZUKU_DATA){document.getElementById('panels').innerHTML='<div class="group"><h3>Website data could not be loaded</h3><p>Make sure site-data.js is beside admin.html.</p></div>';return}
const original=clone(window.SHIZUKU_DATA);let data=clone(original);
data.philosophy??={line1:'In a world that moves quickly,',line2:'we choose to make',line3:'one cup at a time.'};
data.why??={title:'Care lives in\nthe details.',items:[{title:'Freshly whisked',body:'Each cup begins only after your order is received.'},{title:'Oat milk by default',body:'A creamy pairing selected to support—not hide—the tea.'},{title:'Small batch',body:'A focused menu gives us more time for every cup.'},{title:'Made with intention',body:'From the whisk to the handover, nothing is treated as an afterthought.'}]};
const sections=[['Logo','logo'],['Banner','banner'],['Hero','hero'],['Philosophy','philosophy'],['Our Matcha','matcha'],['Why Us','why'],['Matcha Library','library'],['Menu','menu'],['Pictures','pictures'],['Little Updates','updates'],['Contact Us','contact']];
const nav=document.getElementById('nav'),panels=document.getElementById('panels'),frame=document.getElementById('previewFrame');
const safe=value=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const input=(label,path,value,type='text')=>`<label class="field"><span>${label}</span>${type==='textarea'?`<textarea data-path="${path}">${safe(value)}</textarea>`:`<input type="${type}" data-path="${path}" value="${safe(value)}">`}</label>`;
const itemFields=(list,key,fields)=>list.map((item,index)=>`<div class="item"><h3>${safe(item.name||item.title||`Item ${index+1}`)}</h3>${fields.map(field=>input(field[0],`${key}.${index}.${field[1]}`,item[field[1]],field[2]||'text')).join('')}</div>`).join('');
function get(path){return path.split('.').reduce((value,key)=>value?.[key],data)}
function set(path,value){const keys=path.split('.');let target=data;keys.slice(0,-1).forEach(key=>target=target[key]);const key=keys[keys.length-1];target[key]=typeof target[key]==='number'?Number(value):value}
function makePanels(){
nav.innerHTML=sections.map((section,index)=>`<button data-panel="${section[1]}" class="${index?'':'active'}">${section[0]}</button>`).join('');
panels.innerHTML=`
<section class="panel active" data-panel="logo"><h2>Logo</h2><p>Edit the logo used throughout the website.</p><div class="group">${input('Logo file','brand.logo',data.brand.logo)}<div class="row">${input('Desktop size','brand.logoDesktop',data.brand.logoDesktop,'number')}${input('Mobile size','brand.logoMobile',data.brand.logoMobile,'number')}</div></div></section>
<section class="panel" data-panel="banner"><h2>Banner</h2><p>Edit the large opening photograph and website colours.</p><div class="group">${input('Banner picture','hero.image',data.hero.image)}<div class="row">${input('Main green','brand.mainColor',data.brand.mainColor,'color')}${input('Paper colour','brand.paperColor',data.brand.paperColor,'color')}</div></div></section>
<section class="panel" data-panel="hero"><h2>Hero</h2><p>Edit the words shown on the banner.</p><div class="group">${input('Small heading','hero.eyebrow',data.hero.eyebrow)}${input('Main title','hero.title',data.hero.title)}${input('Italic title','hero.titleItalic',data.hero.titleItalic)}${input('Description','hero.body',data.hero.body,'textarea')}<div class="row">${input('Desktop title size','hero.fontSizeDesktop',data.hero.fontSizeDesktop,'number')}${input('Mobile title size','hero.fontSizeMobile',data.hero.fontSizeMobile,'number')}</div></div></section>
<section class="panel" data-panel="philosophy"><h2>Philosophy</h2><p>Edit the three-line brand message.</p><div class="group">${input('Line 1','philosophy.line1',data.philosophy.line1)}${input('Line 2','philosophy.line2',data.philosophy.line2)}${input('Line 3','philosophy.line3',data.philosophy.line3)}</div></section>
<section class="panel" data-panel="matcha"><h2>Our Matcha</h2><p>Edit the matcha introduction and tasting information.</p><div class="group">${input('Title','matcha.title',data.matcha.title,'textarea')}${input('Description','matcha.body',data.matcha.body,'textarea')}<div class="row">${input('Origin','matcha.origin',data.matcha.origin)}${input('Harvest','matcha.harvest',data.matcha.harvest)}</div>${input('Cultivar','matcha.cultivar',data.matcha.cultivar)}${input('Tasting notes','matcha.tastingNotes',data.matcha.tastingNotes)}${input('Finish','matcha.finish',data.matcha.finish)}</div></section>
<section class="panel" data-panel="why"><h2>Why Us</h2><p>Edit the reasons customers choose Shizuku Lab.</p><div class="group">${input('Section title','why.title',data.why.title,'textarea')}${itemFields(data.why.items,'why.items',[['Title','title'],['Description','body','textarea']])}</div></section>
<section class="panel" data-panel="library"><h2>Matcha Library</h2><p>Edit the introduction and cultivar cards.</p><div class="group">${input('Introduction title','library.introTitle',data.library.introTitle,'textarea')}${input('Introduction','library.introBody',data.library.introBody,'textarea')}</div><div class="group">${itemFields(data.library.cultivars,'library.cultivars',[['Name','name'],['Region','region'],['Picture','image'],['Profile','profile','textarea'],['Tag 1','tag1'],['Tag 2','tag2']])}</div></section>
<section class="panel" data-panel="menu"><h2>Menu</h2><p>Edit drinks, descriptions, prices and pictures.</p><div class="group">${itemFields(data.menu,'menu',[['Category','eyebrow'],['Name','name'],['Description','description','textarea'],['Price','price'],['Picture','image']])}</div></section>
<section class="panel" data-panel="pictures"><h2>Pictures</h2><p>Change the main photographs around the website.</p><div class="group">${input('Banner picture','hero.image',data.hero.image)}${input('Our Story picture','story.image',data.story.image)}${input('Our Matcha picture','matcha.image',data.matcha.image)}</div></section>
<section class="panel" data-panel="updates"><h2>Little Updates</h2><p>Edit the three updates near the bottom.</p><div class="group">${itemFields(data.updates,'updates',[['Date or label','date'],['Title','title'],['Content','body','textarea'],['Picture','image']])}</div></section>
<section class="panel" data-panel="contact"><h2>Contact Us</h2><p>Edit collection and contact details.</p><div class="group">${input('Title','contact.title',data.contact.title,'textarea')}${input('Collection information','contact.collection',data.contact.collection,'textarea')}${input('Instagram name','contact.instagram',data.contact.instagram)}${input('Instagram link','contact.instagramUrl',data.contact.instagramUrl)}${input('Order link','contact.orderUrl',data.contact.orderUrl)}</div></section>`;
}
function preview(){frame.contentWindow.postMessage({type:'SHIZUKU_PREVIEW',data},'*')}
makePanels();
nav.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;document.querySelectorAll('.nav button,.panel').forEach(element=>element.classList.remove('active'));button.classList.add('active');document.querySelector(`.panel[data-panel="${button.dataset.panel}"]`)?.classList.add('active')});
panels.addEventListener('input',event=>{if(!event.target.dataset.path)return;set(event.target.dataset.path,event.target.value);preview()});
document.getElementById('save').onclick=()=>{localStorage.setItem('shizuku-admin-preview',JSON.stringify(data));preview();alert('Preview saved on this device.')};
document.getElementById('reset').onclick=()=>{data=clone(original);data.philosophy??={line1:'In a world that moves quickly,',line2:'we choose to make',line3:'one cup at a time.'};data.why??={title:'Care lives in\nthe details.',items:[]};localStorage.removeItem('shizuku-admin-preview');frame.contentWindow.postMessage({type:'SHIZUKU_CLEAR_PREVIEW'},'*');makePanels()};
document.getElementById('export').onclick=()=>{const blob=new Blob(['window.SHIZUKU_DATA = '+JSON.stringify(data,null,2)+';\n'],{type:'text/javascript'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='site-data.js';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)};
document.querySelector('.devices').onclick=event=>{const button=event.target.closest('button');if(!button)return;document.querySelectorAll('.devices button').forEach(element=>element.classList.remove('active'));button.classList.add('active');document.getElementById('framewrap').className='framewrap '+(button.dataset.device==='mobile'?'mobile':'')};
})();
