(() => {
const clone=value=>JSON.parse(JSON.stringify(value));
if(!window.SHIZUKU_DATA){document.getElementById('panels').innerHTML='<div class="group"><h3>Website data could not be loaded</h3><p>Make sure site-data.js is beside admin.html.</p></div>';return}
const original=clone(window.SHIZUKU_DATA);let data=clone(original);
data.philosophy??={line1:'In a world that moves quickly,',line2:'we choose to make',line3:'one cup at a time.'};
data.why??={title:'Care lives in\nthe details.',items:[{title:'Freshly whisked',body:'Each cup begins only after your order is received.'},{title:'Oat milk by default',body:'A creamy pairing selected to support—not hide—the tea.'},{title:'Small batch',body:'A focused menu gives us more time for every cup.'},{title:'Made with intention',body:'From the whisk to the handover, nothing is treated as an afterthought.'}]};
data.library.colourStudyImage??='matcha-colour-study.jpg';
data.library.topics??=[{id:'what-is-matcha',title:'What is matcha?',summary:'From shaded tencha leaf to a fine powder.'},{id:'harvest',title:'First vs second harvest',summary:'Why harvest timing changes flavour and texture.'},{id:'picking',title:'Hand-picked or machine-picked?',summary:'Selection, consistency and what can affect the cup.'},{id:'grinding',title:'How matcha is ground',summary:'Stone milling, modern milling and why heat matters.'},{id:'ceremonial',title:'“Ceremonial grade” explained',summary:'A useful label, but not one official Japanese standard.'},{id:'atlas',title:'Matcha Atlas',summary:'Explore a few of Japan’s best-known tea regions.'},{id:'cultivars',title:'Matcha Colour Study',summary:'Compare seven real single-cultivar matcha powders.'}];
const sections=[['Logo','logo'],['Banner','banner'],['Hero','hero'],['Philosophy','philosophy'],['Our Story','story'],['Our Matcha','matcha'],['Why Us','why'],['Matcha Library','library'],['Menu','menu'],['Pictures','pictures'],['Little Updates','updates'],['Contact Us','contact']];
const nav=document.getElementById('nav'),panels=document.getElementById('panels'),frame=document.getElementById('previewFrame');
const safe=value=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const input=(label,path,value,type='text')=>`<label class="field"><span>${label}</span>${type==='textarea'?`<textarea data-path="${path}">${safe(value)}</textarea>`:type==='image'?`<img src="${safe(value)}" alt="" style="display:block;width:100%;height:180px;object-fit:contain;border-radius:8px;margin-bottom:8px;background:#eee"><input type="file" accept="image/*" data-image-path="${path}"><span style="display:flex;gap:7px;margin-top:8px"><button type="button" data-rotate-image="${path}" data-direction="left" style="flex:1;border:1px solid #123f2f;background:white;border-radius:999px;padding:7px;cursor:pointer">↶ Rotate left</button><button type="button" data-rotate-image="${path}" data-direction="right" style="flex:1;border:1px solid #123f2f;background:white;border-radius:999px;padding:7px;cursor:pointer">Rotate right ↷</button></span>`:`<input type="${type}" data-path="${path}" value="${safe(value)}">`}</label>`;
const itemFields=(list,key,fields)=>list.map((item,index)=>`<div class="item"><h3>${safe(item.name||item.title||`Item ${index+1}`)}</h3>${fields.map(field=>input(field[0],`${key}.${index}.${field[1]}`,item[field[1]],field[2]||'text')).join('')}</div>`).join('');
function get(path){return path.split('.').reduce((value,key)=>value?.[key],data)}
function set(path,value){const keys=path.split('.');let target=data;keys.slice(0,-1).forEach(key=>target=target[key]);const key=keys[keys.length-1];target[key]=typeof target[key]==='number'?Number(value):value}
function makePanels(){
nav.innerHTML=sections.map((section,index)=>`<button data-panel="${section[1]}" class="${index?'':'active'}">${section[0]}</button>`).join('');
panels.innerHTML=`
<section class="panel active" data-panel="logo"><h2>Logo</h2><p>Choose the logo from your Photo Library or Files.</p><div class="group">${input('Logo picture','brand.logo',data.brand.logo,'image')}<div class="row">${input('Desktop size','brand.logoDesktop',data.brand.logoDesktop,'number')}${input('Mobile size','brand.logoMobile',data.brand.logoMobile,'number')}</div></div></section>
<section class="panel" data-panel="banner"><h2>Banner</h2><p>Choose the opening photograph and edit website colours.</p><div class="group">${input('Banner picture','hero.image',data.hero.image,'image')}<div class="row">${input('Main green — green sections','brand.mainColor',data.brand.mainColor,'color')}${input('Paper colour — light sections','brand.paperColor',data.brand.paperColor,'color')}</div><p style="margin:10px 0 0;color:#667168;font-size:12px">Paper colour changes the light website sections, not the banner photograph. The preview will jump to the relevant section when you choose a colour.</p></div></section>
<section class="panel" data-panel="hero"><h2>Hero</h2><p>Edit the words shown on the banner.</p><div class="group">${input('Small heading','hero.eyebrow',data.hero.eyebrow)}${input('Main title','hero.title',data.hero.title)}${input('Italic title','hero.titleItalic',data.hero.titleItalic)}${input('Description','hero.body',data.hero.body,'textarea')}<div class="row">${input('Desktop title size','hero.fontSizeDesktop',data.hero.fontSizeDesktop,'number')}${input('Mobile title size','hero.fontSizeMobile',data.hero.fontSizeMobile,'number')}</div></div></section>
<section class="panel" data-panel="philosophy"><h2>Philosophy</h2><p>Edit the three-line brand message.</p><div class="group">${input('Line 1','philosophy.line1',data.philosophy.line1)}${input('Line 2','philosophy.line2',data.philosophy.line2)}${input('Line 3','philosophy.line3',data.philosophy.line3)}</div></section>
<section class="panel" data-panel="story"><h2>Our Story</h2><p>Edit the story section and choose its picture.</p><div class="group">${input('Title','story.title',data.story.title,'textarea')}${input('Paragraph 1','story.paragraph1',data.story.paragraph1,'textarea')}${input('Paragraph 2','story.paragraph2',data.story.paragraph2,'textarea')}${input('Story picture','story.image',data.story.image,'image')}</div></section>
<section class="panel" data-panel="matcha"><h2>Our Matcha</h2><p>Edit the matcha introduction and tasting information.</p><div class="group">${input('Title','matcha.title',data.matcha.title,'textarea')}${input('Description','matcha.body',data.matcha.body,'textarea')}<div class="row">${input('Origin','matcha.origin',data.matcha.origin)}${input('Harvest','matcha.harvest',data.matcha.harvest)}</div>${input('Cultivar','matcha.cultivar',data.matcha.cultivar)}${input('Tasting notes','matcha.tastingNotes',data.matcha.tastingNotes)}${input('Finish','matcha.finish',data.matcha.finish)}</div></section>
<section class="panel" data-panel="why"><h2>Why Us</h2><p>Edit the reasons customers choose Shizuku Lab.</p><div class="group">${input('Section title','why.title',data.why.title,'textarea')}${itemFields(data.why.items,'why.items',[['Title','title'],['Description','body','textarea']])}</div></section>
<section class="panel" data-panel="library"><h2>Matcha Library</h2><p>Edit all seven topics. Use Preview topic to open that topic on the right.</p><div class="group">${input('Introduction title','library.introTitle',data.library.introTitle,'textarea')}${input('Introduction','library.introBody',data.library.introBody,'textarea')}${input('Matcha Colour Study main image','library.colourStudyImage',data.library.colourStudyImage,'image')}</div><div class="group">${data.library.topics.map((topic,index)=>`<div class="item"><h3>${index+1}. ${safe(topic.title)}</h3>${input('Topic title',`library.topics.${index}.title`,topic.title)}${input('Short description',`library.topics.${index}.summary`,topic.summary,'textarea')}<button type="button" data-preview-topic="${topic.id}" style="border:1px solid #123f2f;background:white;border-radius:999px;padding:8px 12px;cursor:pointer">Preview topic →</button></div>`).join('')}</div><div class="group"><h3>Matcha Colour Study cultivar cards</h3>${itemFields(data.library.cultivars,'library.cultivars',[['Name','name'],['Region','region'],['Picture','image','image'],['Profile','profile','textarea'],['Tag 1','tag1'],['Tag 2','tag2']])}</div></section>
<section class="panel" data-panel="menu"><h2>Menu</h2><p>Edit drinks, descriptions, prices and pictures.</p><div class="group">${itemFields(data.menu,'menu',[['Category','eyebrow'],['Name','name'],['Description','description','textarea'],['Price','price'],['Picture','image','image']])}</div></section>
<section class="panel" data-panel="pictures"><h2>Pictures</h2><p>Choose the main photographs from your Photo Library or Files.</p><div class="group">${input('Banner picture','hero.image',data.hero.image,'image')}${input('Our Story picture','story.image',data.story.image,'image')}${input('Our Matcha picture','matcha.image',data.matcha.image,'image')}</div></section>
<section class="panel" data-panel="updates"><h2>Little Updates</h2><p>Edit the three updates near the bottom.</p><div class="group">${itemFields(data.updates,'updates',[['Date or label','date'],['Title','title'],['Content','body','textarea'],['Picture','image','image']])}</div></section>
<section class="panel" data-panel="contact"><h2>Contact Us</h2><p>Edit collection and contact details.</p><div class="group">${input('Title','contact.title',data.contact.title,'textarea')}${input('Collection information','contact.collection',data.contact.collection,'textarea')}${input('Instagram name','contact.instagram',data.contact.instagram)}${input('Instagram link','contact.instagramUrl',data.contact.instagramUrl)}${input('Order link','contact.orderUrl',data.contact.orderUrl)}</div></section>`;
}
function preview(){frame.contentWindow.postMessage({type:'SHIZUKU_PREVIEW',data},'*')}
function prepareImage(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error('Could not read this image.'));reader.onload=()=>{const image=new Image();image.onerror=()=>reject(new Error('This image format could not be opened.'));image.onload=()=>{const maximum=1800,scale=Math.min(1,maximum/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);const transparent=file.type==='image/png';resolve(canvas.toDataURL(transparent?'image/png':'image/jpeg',transparent?undefined:.86))};image.src=reader.result};reader.readAsDataURL(file)})}
function rotateImage(source,direction){return new Promise((resolve,reject)=>{const image=new Image();image.onerror=()=>reject(new Error('This picture could not be rotated.'));image.onload=()=>{const canvas=document.createElement('canvas');canvas.width=image.height;canvas.height=image.width;const context=canvas.getContext('2d');context.translate(canvas.width/2,canvas.height/2);context.rotate((direction==='left'?-1:1)*Math.PI/2);context.drawImage(image,-image.width/2,-image.height/2);resolve(canvas.toDataURL('image/jpeg',.88))};image.src=source})}
makePanels();
nav.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;document.querySelectorAll('.nav button,.panel').forEach(element=>element.classList.remove('active'));button.classList.add('active');document.querySelector(`.panel[data-panel="${button.dataset.panel}"]`)?.classList.add('active');const targets={logo:'home',banner:'home',hero:'home',philosophy:'philosophy',story:'story',matcha:'matcha',why:'why',library:'library',menu:'menu',pictures:'story',updates:'journal',contact:'contact'};frame.contentWindow.postMessage({type:'SHIZUKU_NAVIGATE',target:targets[button.dataset.panel]},'*')});
panels.addEventListener('input',event=>{if(!event.target.dataset.path)return;set(event.target.dataset.path,event.target.value);preview();const path=event.target.dataset.path;if(path==='brand.paperColor'||path==='brand.mainColor'){setTimeout(()=>{const target=path==='brand.paperColor'?'story':'matcha';frame.contentWindow.document.getElementById(target)?.scrollIntoView({behavior:'smooth',block:'start'})},80)}});
panels.addEventListener('change',async event=>{const path=event.target.dataset.imagePath,file=event.target.files?.[0];if(!path||!file)return;const label=event.target.closest('.field'),oldText=label.querySelector('span').textContent;label.querySelector('span').textContent='Preparing picture…';try{const imageData=await prepareImage(file);set(path,imageData);label.querySelector('img').src=imageData;preview()}catch(error){alert(error.message)}finally{label.querySelector('span').textContent=oldText}});
panels.addEventListener('click',async event=>{const topicButton=event.target.closest('[data-preview-topic]');if(topicButton){preview();frame.contentWindow.postMessage({type:'SHIZUKU_OPEN_LIBRARY',topic:topicButton.dataset.previewTopic},'*');return}const rotateButton=event.target.closest('[data-rotate-image]');if(!rotateButton)return;const oldText=rotateButton.textContent;rotateButton.disabled=true;rotateButton.textContent='Rotating…';try{const path=rotateButton.dataset.rotateImage,rotated=await rotateImage(get(path),rotateButton.dataset.direction);set(path,rotated);rotateButton.closest('.field').querySelector('img').src=rotated;preview()}catch(error){alert(error.message)}finally{rotateButton.disabled=false;rotateButton.textContent=oldText}});
document.getElementById('save').onclick=()=>{try{localStorage.setItem('shizuku-admin-preview',JSON.stringify(data));preview();alert('Preview saved on this device.')}catch(error){preview();alert('The preview works, but there are too many large pictures to save inside Safari. You can still export site-data.js.')}};
document.getElementById('reset').onclick=()=>{data=clone(original);data.philosophy??={line1:'In a world that moves quickly,',line2:'we choose to make',line3:'one cup at a time.'};data.why??={title:'Care lives in\nthe details.',items:[]};localStorage.removeItem('shizuku-admin-preview');frame.contentWindow.postMessage({type:'SHIZUKU_CLEAR_PREVIEW'},'*');makePanels()};
document.getElementById('export').onclick=()=>{const blob=new Blob(['window.SHIZUKU_DATA = '+JSON.stringify(data,null,2)+';\n'],{type:'text/javascript'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='site-data.js';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)};
document.querySelector('.devices').onclick=event=>{const button=event.target.closest('button');if(!button)return;document.querySelectorAll('.devices button').forEach(element=>element.classList.remove('active'));button.classList.add('active');document.getElementById('framewrap').className='framewrap '+(button.dataset.device==='mobile'?'mobile':'')};
})();
